apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-apply
  namespace: tf-automation-gate
spec:
  workspaces:
    - name: source
  steps:
    - name: tf-init-apply
      image: hashicorp/terraform:1.6.0
      workingDir: $(workspaces.source.path)/terraform
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN # Added this based on your jq output
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SESSION_TOKEN
      script: |
        #!/bin/sh
        terraform init
        terraform apply -auto-approve