apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-executor
  namespace: tf-automation-gate
spec:
  params:
    - name: git-url
      description: "The HTTPS URL of the repo to clone"
    - name: terraform-dir        # <--- ADD THIS BLOCK
      description: "The sub-folder"
      default: "."
    - name: action
      default: "apply"
      description: "Set to 'apply' or 'destroy' for Step 5"
  workspaces:
    - name: source
      description: "This is our 5Gi tf-pvc workbench"
  steps:
    - name: fetch-source
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        # Clean the workspace so old runs from other repos don't conflict
        rm -rf ./* .??* 
        git clone $(params.git-url)/$(params.terraform-dir) .

    - name: tf-init-execute
      image: hashicorp/terraform:1.6.0
      workingDir: $(workspaces.source.path)/$(params.terraform-dir)
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
      script: |
        #!/bin/sh
        # 1. Define where the code actually is
        TF_DIR="$(workspaces.source.path)/$(params.terraform-dir)"

        # 2. CREATE the backend file directly in that folder
        # This ensures Terraform SEES it without us having to 'cd' into it.
        cat <<EOF > ${TF_DIR}/backend_generated.tf
        terraform {
        backend "s3" {
        bucket = "sp-01102026-aws-kub"
        key    = "openshift-project/$(params.project-name).tfstate"
        region = "us-east-1"
        }
        EOF

        # 3. Use -chdir to point Terraform to the folder
        # This replaces 'cd' entirely.
        terraform -chdir=${TF_DIR} init -input=false

        # 4. Execute the Action
        if [ "$(params.action)" == "destroy" ]; then
        terraform -chdir=${TF_DIR} destroy -auto-approve
        else
        terraform -chdir=${TF_DIR} apply -auto-approve
        fi