apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-pvc
  namespace: tf-automation-gate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # We don't need much for a few .tf files