apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modular-terraform-gate
  namespace: argocd # ArgoCD usually lives here
spec:
  project: default
  source:
    repoURL: 'https://github.com/sprakriy/ArgoCD-Github-openshift.git'
    targetRevision: HEAD
    path: tekton # Only watch the terraform modular folder
    directory:
      recurse: true # Watch all subfolders in tekton
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tf-automation-gate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true